# "all" is name of the default target, running "make" without params would use it
all: Test

# for C++, replace CC (c compiler) with CXX (c++ compiler) which is used as default linker
CC=$(CXX)

# tell which files should be used, .cpp -> .o make would do automatically
# MSCKFTest: file1.o file2.o

Test: test.o